quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB.USER}
    password: ${DB.PASSWORD}
    jdbc:
      url: ${DB.URL}
      driver: org.postgresql.Driver
  hibernate-orm:
    database:
      generation: update
  resteasy:
    path: /api
  swagger-ui:
    path: /api/docs
