quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB.USER}
    password: ${DB.PASSWORD}
    jdbc:
      url: ${DB.URL}
      driver: org.postgresql.Driver
  hibernate-orm:
    database:
      generation: update
  resteasy:
    path: /api
  swagger-ui:
    path: /api/docs

mp:
  jwt:
    verify:
      publickey:
        location: public.pem
      issuer: https://silent-passenger.com

api:
  key: ${RAPID.API.GEOCODE.KEY}
  apiHost: ${RAPID.API.GEOCODE.HOST}

geocoding/mp-rest/url: https://forward-reverse-geocoding.p.rapidapi.com/v1/forward
geocoding/mp-rest/scope: javax.inject.Singleton
router/mp-rest/url: http://router.project-osrm.org/route/v1/car/
router/mp-rest/scope: javax.inject.Singleton
